site_name:        Persa.jl
repo_url:         https://github.com/JuliaRecsys/Persa.jl
site_description: Recommender System framework for Julia.
site_author:      JuliaRecsys

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code

docs_dir: 'build'

pages:
  - Home: 'index.md'
  - Getting Started: 'man/getting_started.md'
